from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "extension" / "source"
DEFAULT_OUTPUT = ROOT / "extension" / "packet-tracer-visual-mcp-script-engine.js"


def _read(name: str) -> str:
    return (SOURCE_DIR / name).read_text(encoding="utf-8").strip() + "\n"


def build(interface_url: str | None = None) -> str:
    if interface_url is None:
        interface_url = (SOURCE_DIR / "interface" / "index.html").resolve().as_uri()

    parts = [
        "// Generated by scripts/build_script_engine.py.\n",
        "// Import and run this file in Packet Tracer Script Engine.\n",
        "var PTV_INTERFACE_URL = " + repr(interface_url) + ";\n",
        "\n// ---- pt_api.js ----\n",
        _read("pt_api.js"),
        "\n// ---- runcode.js ----\n",
        _read("runcode.js"),
        "\n// ---- window.js ----\n",
        _read("window.js"),
        "\n// ---- main.js ----\n",
        _read("main.js"),
    ]
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the Packet Tracer Script Engine entry file.")
    parser.add_argument("--interface-url", default=None, help="Override the bridge UI URL.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT, help="Output JavaScript file.")
    args = parser.parse_args()

    output = args.out.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build(args.interface_url), encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
